name: mix_lint_test
description: A sample command-line application.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  mix:
    path: ../mix
  mix_lint:
    path: ../mix_lint

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.1
  # analyzer: ^6.0.0
  # analyzer_plugin: ^0.11.2
  # test: ^1.24.9
