name: mix_annotations
description: Annotations for mix and mix_generator
version: 4.0.0
repository: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.0.6 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
