name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 1.0.0-beta.12
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.10.6 <4.0.0"
  
dependencies:
  meta: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter
  dart_code_metrics_presets: 2.9.0

flutter:
  assets:
    - test_resources/
