name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 1.0.0-beta.6
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.17.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.2
  test_cov_console: ^0.2.2
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  dart_code_metrics_presets: ^2.8.0
  path: ^1.8.3
  mockito: ^5.4.2
  meta: ^1.9.1

flutter:
  assets:
    - test_resources/
