name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 0.0.7
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.0
  test_cov_console: ^0.2.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.21.0
