name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 0.0.6
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.4
  test_cov_console: ^0.0.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.13.0
flutter:
