name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 1.6.0
homepage: https://github.com/leoafarias/mix
repository: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"
  
dependencies:
  mix_annotations: ^0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  dart_code_metrics_presets: ^2.14.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mix_generator: ^0.4.0

screenshots:
  - description: The Mix logo.
    path: screenshots/logo.png
