name: mix
description: An expressive way to effortlessly build design systems in Flutter.
version: 1.4.2
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"
  
dependencies:
  mix_annotations: ^0.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  dart_code_metrics_presets: ^2.13.0
  build_runner: ^2.4.9
  mix_generator: ^0.2.2+2

# flutter:
  # assets:

