name: mix_lint
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/leoafarias/mix

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  analyzer: ^6.0.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
