blank_issues_enabled: true
contact_links:
  - name: Do you need any help?
    url: https://github.com/conceptadev/mix/discussions/new?category=q-a
    about: If you have any questions, please ask us here!