name: remix
description: Completely unstyled, widgets designed to integrate with Mix
repository: https://github.com/conceptadev/mix/tree/main/packages/remix
homepage: https://www.fluttermix.com/

version: 0.0.4+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.6.0
  mix_annotations: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # custom_lint: ^0.6.4
  # mix_lint: ^0.1.1
  mix_generator: ^0.4.0
  build_runner: ^2.4.9
  #lint
  flutter_lints: ^4.0.0
  dart_code_metrics_presets: ^2.14.0
  

flutter:
  uses-material-design: true
