name: remix
description: Completely unstyled, widgets designed to integrate with Mix

version: 0.0.2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.4.0
  mix_annotations: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mix_generator: ^0.2.2
  build_runner: ^2.4.9
  dart_code_metrics_presets: ^2.14.0
  

flutter:
  uses-material-design: true
