name: mix_generator
description: A code generator for Mix, an expressive way to effortlessly build design systems in Flutter.
version: 0.2.0+1
homepage: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.10.6"
  
dependencies:
  mix_annotations: ^2.0.0-beta.2
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.1.0
  dart_style: ^2.3.6
  collection: ^1.17.1
  build_config: ^1.1.1
  

dev_dependencies:
  dart_code_metrics_presets: ^2.13.0
  build_runner: ^2.4.9
  build_test: ^2.2.2
  source_gen_test: ^1.0.6