name: mix_generator
description: A code generator for Mix, an expressive way to effortlessly build design systems in Flutter.
version: 0.3.3
homepage: https://github.com/conceptadev/mix

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  mix_annotations: ^0.3.2
  build: ^2.4.1
  source_gen: ^2.0.0
  analyzer: ^7.3.0
  dart_style: ^3.0.1
  collection: ^1.17.1
  build_config: ^1.1.1
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.4
  build_runner: ^2.4.9
  build_test: ^2.2.2
  source_gen_test: ^1.0.6
  # Lint
  dart_code_metrics_presets: ^2.14.0
  flutter_lints: ^4.0.0
