name: themed_button
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.10.6"

dependencies:
  flutter:
    sdk: flutter
  mix: 
    path: ../../packages/mix
  custom_lint:
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.6
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mix_lint: 
    path: ../../packages/mix_lint
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
